"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 18:22:56.922531
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prospect_ids', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_created_at'), 'analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('encrypted_tokens', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_integration')
    )
    op.create_index(op.f('ix_integrations_created_at'), 'integrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'ANALYZED', 'REVIEW', 'APPROVED', 'CONTACTED', 'REPLIED', 'QUALIFIED', 'PROPOSAL', 'WON', 'LOST', name='prospectstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('takeover_required', sa.Boolean(), nullable=False),
    sa.Column('taken_over_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('lead_score IS NULL OR (lead_score >= 0 AND lead_score <= 100)', name='ck_lead_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prospect_user_score', 'prospects', ['user_id', 'lead_score'], unique=False)
    op.create_index('ix_prospect_user_status', 'prospects', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_prospects_company'), 'prospects', ['company'], unique=False)
    op.create_index(op.f('ix_prospects_created_at'), 'prospects', ['created_at'], unique=False)
    op.create_index(op.f('ix_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_index(op.f('ix_prospects_is_demo'), 'prospects', ['is_demo'], unique=False)
    op.create_index(op.f('ix_prospects_lead_score'), 'prospects', ['lead_score'], unique=False)
    op.create_index(op.f('ix_prospects_linkedin_url'), 'prospects', ['linkedin_url'], unique=False)
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    op.create_index(op.f('ix_prospects_user_id'), 'prospects', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('business', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ai_provider', sa.String(length=32), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('message_tone', sa.String(length=50), nullable=False),
    sa.Column('followup_1_days', sa.Integer(), nullable=False),
    sa.Column('followup_2_days', sa.Integer(), nullable=False),
    sa.Column('meeting_title', sa.String(length=200), nullable=False),
    sa.Column('meeting_duration', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_intent'), 'conversations', ['intent'], unique=False)
    op.create_index(op.f('ix_conversations_prospect_id'), 'conversations', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('lead_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('need', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('authority', sa.Integer(), nullable=False),
    sa.Column('timeline', sa.Integer(), nullable=False),
    sa.Column('current_solution', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id')
    )
    op.create_index(op.f('ix_lead_qualifications_created_at'), 'lead_qualifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_qualifications_score'), 'lead_qualifications', ['score'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_event_link', sa.String(length=500), nullable=True),
    sa.Column('calendar_synced', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_created_at'), 'meetings', ['created_at'], unique=False)
    op.create_index(op.f('ix_meetings_prospect_id'), 'meetings', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_meetings_start_at'), 'meetings', ['start_at'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_created_at'), 'outreach', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_prospect_id'), 'outreach', ['prospect_id'], unique=False)
    op.create_table('prospect_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('website_analysis', sa.JSON(), nullable=True),
    sa.Column('website_retrieved', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'analysis_version', name='uq_analysis_version')
    )
    op.create_index(op.f('ix_prospect_analyses_analyzed_at'), 'prospect_analyses', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_prospect_analyses_lead_score'), 'prospect_analyses', ['lead_score'], unique=False)
    op.create_index(op.f('ix_prospect_analyses_prospect_id'), 'prospect_analyses', ['prospect_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_prospect_analyses_prospect_id'), table_name='prospect_analyses')
    op.drop_index(op.f('ix_prospect_analyses_lead_score'), table_name='prospect_analyses')
    op.drop_index(op.f('ix_prospect_analyses_analyzed_at'), table_name='prospect_analyses')
    op.drop_table('prospect_analyses')
    op.drop_index(op.f('ix_outreach_prospect_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_created_at'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_start_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_prospect_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_at'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_lead_qualifications_score'), table_name='lead_qualifications')
    op.drop_index(op.f('ix_lead_qualifications_created_at'), table_name='lead_qualifications')
    op.drop_table('lead_qualifications')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_prospect_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_intent'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_prospects_user_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_linkedin_url'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_lead_score'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_is_demo'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_email'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_created_at'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_company'), table_name='prospects')
    op.drop_index('ix_prospect_user_status', table_name='prospects')
    op.drop_index('ix_prospect_user_score', table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_created_at'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_created_at'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    sa.Enum(name='prospectstatus').drop(op.get_bind(), checkfirst=True)
